parameters:
  product_inventory.manager.email: 'bajomodavid@gmail.com'
  product_inventory.csv_location: ''

services:
  BajomoDavid\ProductInventoryBundle\Command\:
    resource: '../src/Command/*'
    tags: [ 'console.command' ]