parameters:
  product_inventory.manager.email: 'bajomodavid@gmail.com'
  product_inventory.csv_location: ''

services:
  BajomoDavid\ProductInventoryBundle\Command\:
    resource: '../src/Command/*'
    arguments:
      $projectDir: "%kernel.project_dir%"
    tags: [ 'console.command' ]

  app.inventory_import:
    class: BajomoDavid\ProductInventoryBundle\Controller\ImportData
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'