parameters:
  product_inventory.manager.email: 'bajomodavid@gmail.com'
  product_inventory.csv_location: ''
  kernel.project_dir: "%env(PRODUCT_INVENTORY_FILE_ROOT)%"

services:
  app.command.inventory_read:
    class: BajomoDavid\ProductInventoryBundle\Command\ReadStockData
    tags: [ 'console.command' ]

  app.inventory_read:
    class: BajomoDavid\ProductInventoryBundle\Controller\ReadCsvFile
    arguments:
      $projectDir: "%kernel.project_dir%"

  BajomoDavid\ProductInventoryBundle\Controller\ReadCsvFile: '@app.inventory_read'

  app.inventory_import:
    class: BajomoDavid\ProductInventoryBundle\Controller\ImportData
    arguments:
      $entityManager: "@doctrine.orm.entity_manager"